# justfile
#
# https://github.com/casey/just

project := "{{ project_name }}"


# Show available commands.
help:
  @just -l


# Run the app.
run:{% raw %}
  poetry run {{project}}
{% endraw %}
# Run linters and formatters.
fmt:
  poetry run isort src/
  poetry run autoflake --in-place --remove-unused-variables --remove-all-unused-imports --expand-star-imports -r src/
  poetry run black src/
  poetry run flake8 src/

# Run tests.
test:
  poetry run pytest -v
  poetry run mypy src

# Run security scanners.
scan:
  poetry run bandit -r . -c pyproject.toml 
  poetry run safety check


# First time project setup.
init:
  poetry check
  poetry install
  pre-commit install
  pre-commit install-hooks
  pre-commit autoupdate
  pre-commit run -av


# # Package using shiv.
# shiv:
#   poetry run shiv . -p '/usr/bin/env python3' -o dist/{{project}}.pyz -c {{project}}
#
#
# # Package using pex.
# pex:
#   pex . -o dist/{{project}}.pex -c {{project}}


# Remove temporary files.
clean:
  -rm dist/{{project}}-*.tar.gz
  -rm dist/{{project}}.pex
  -rm dist/{{project}}.pyz
  -rm dist/{{project}}.whl
  -rm requirements.txt
